### ISSUE TITLE
Need to have eventID variables and table key to match data model

### ISSUE THREAD

**Issue by ZakBrinlee** [ActoKids/api#31]
The Lambda function and DynamoDB have the wrong syntax for the event_id variable. 

The code currently has ID and eventID as variables and the table key. The data model has the id stored as **event_id**. The code needs to reflect the data model for consistency. 

Wiki for [Data Model](https://github.com/ActoKids/api/wiki/Data-Model)

**Comment by T-travis** [comment]
I think this can wait until we put our lambdas together accordingly hopefully in our next sprint.

**Comment by T-travis** [comment]
Updated and making PR now.  PR: https://github.com/ActoKids/api/pull/48
