### ISSUE TITLE
Configure API Gateway Dev endpoints

### ISSUE THREAD

**Issue by ZakBrinlee** [ActoKids/api#38]
Configure API Gateway with domains and SSL for all endpoints for the Dev environment. 

**STEPS FOR SPRINT:**
- Teammates from the DevOps for this task: Lyndon, Amy & Dawitt
- Followed the process provided in Jon's [wiki](https://github.com/ActoKids/api/wiki/API-accessability-via-HTTPS-custom-domain) on creating a custom domain for API Gateway.
- What did you do on Route 53: This part of the task was handled by Lyndon, I provided him the API alias as the Target Domain name. 
- What did you do on API Gateway: These steps are provided in Jon's [wiki](https://github.com/ActoKids/api/wiki/API-accessability-via-HTTPS-custom-domain). I created an API specifically for the Dev environment in the Oregon region. 
- What did you do on Certificate Manager:  These steps are provided in Jon's wiki. I requested a certificate for **api-dev.2edusite.com**
- Lambda Function: Dawitt created a Lambda Function in the Oregon region for me. I set it the show a response message to test for this sprint.
![ak-api-dev-url-lambda](https://user-images.githubusercontent.com/22527777/53906785-9aa20d80-4000-11e9-818e-36defc614cd3.PNG)
- Dev Environment Demo: [https://api-dev.2edusite.com/v1/events](https://api-dev.2edusite.com/v1/events)
- Region: Oregon
- DevOps helped provide me with the necessary permissions for Cert. Manager, API Gateway, Lambda so I could complete this sprint. See bug links below for more info on this. 

**Time Spent**
Estimated Time: 4 hours
Time Spent: 6 hours

**BUGS CREATED IN DEVOPS REPO**
- [DevOps BUG #34 ](https://github.com/ActoKids/devops/issues/34)
- [DevOps BUG #36](https://github.com/ActoKids/devops/issues/36)

**Wiki Page**
- [Configure API GateWay Development Endpoint](https://github.com/ActoKids/api/wiki/Configure-API-GateWay-Development-Endpoint)

**Pull Request**
- None for this sprint; no coding performed

**Testing/Reviews I did for my team**
- [Travis - Configure API GateWay Production Endpoint](https://github.com/ActoKids/api/issues/37)
-- My review and notes were provided in a comment since there was no code to push to GitHub
- [Alex - Configure API GateWay 1Box endpoints](https://github.com/ActoKids/api/issues/39)
-- My review and notes were provided in a comment since there was no code to push to GitHub
- [Travis - BUG Fix PR](https://github.com/ActoKids/api/pull/48)
-- Reviewed the code and confirmed it is using the correct event_id variable names in the code and DynamoDB table. Tested new curl commands and got the expected results

**Bugs assigned to me**
- [API Team BUG #47 ](https://github.com/ActoKids/api/issues/47)
-- Closed
- [Bug: Confirm Cognito config, UITeam/API Team](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/87)
-- In progress

**Comment by ZakBrinlee** [comment]
Worked with Lyndon, Dawitt and Amy on DevOps team to complete this Task. 

**Thank you**

BUG Issue created for permissions to Certificate Manager and API Gateway for Oregon Region
[Created BUG](https://github.com/ActoKids/devops/issues/34)
BUG Issue created for permissions to Create Lambda Function permissions for Oregon Region
[Created BUG](https://github.com/ActoKids/devops/issues/36)

Note: 
Unable to add TAGS or Assignees to Issues created for/in DevOps repo

**Comment by Enshaedn** [comment]
**Review by Alex Clontz:**
Development endpoint URL is configured and working.

**Testing:**
Tested the endpoint and confirmed it is working.
> https://api-dev.2edusite.com/v1/events
![image](https://user-images.githubusercontent.com/23545971/53755111-93e19200-3e6a-11e9-9305-cf312a4064d7.png)

**Notes:**
Must use HTTPS - true for every regional setup. Certificate requires HTTPS and there is no re-route setup for HTTP for regional. Also, while I understand the reason for creating everything manually to try to test it I think it isn't the best solution for the prod and dev regions as it is giving our team access they shouldn't have and circumventing the TravisCI pipeline. Therefore I created a [ticket/bug](https://github.com/ActoKids/devops/issues/37) in the DevOps repo noting that TravisCI isn't doing what it is supposed to be doing.

**Comment by MrSamsa42** [comment]
I reviewed the wiki and outline of the steps performed for this sprint.  Everything looks good.  I tested the demo endpoint and confirmed that it works.  

![image](https://user-images.githubusercontent.com/27866709/53756408-ec665e80-3e6d-11e9-851f-7aff45cfa14a.png)
