### ISSUE TITLE
actokids.yaml and event_model.json naming questions

### ISSUE THREAD

**Issue by T-travis** [ActoKids/api#49]
**Description**
In actokids.yaml we have a path **'/events/{eventID}'** and a param  **'parameters: - name: eventID'** and in event_model.json we have **'event_id'**.  From this I used eventID for the PK in DynamoDB and the path param in the endpoint as shown above.  See this [issue](https://github.com/ActoKids/api/issues/31).  I updated the DynamoDB PK to be event_id but kept the path the same.

**Possible Resolutions**
- leave as is now
- change path param and path to be events/event_id to match the event_model and have all occurrences of event_id be the same
- other

**Comment by Enshaedn** [comment]
Fixed with PR #57
