### ISSUE TITLE
create event json file

### ISSUE THREAD

**Issue by kdanepetersen** [ActoKids/api#5]
research information about json files
research information about data diagrams
review information about github
review mobile actokids application
obtain and review original json, original organization list to determine data needed.
create json file for events.
review with API, UI, and Crawler teams for feedback.
Push to github

**Comment by kdanepetersen** [comment]
Estimated time: 12 hours
Actual time to date:  12 hours

**Comment by Enshaedn** [comment]
Closing issue as event.json was added to wiki and this was completed.
