### ISSUE TITLE
HTTP Status handling for API and Proxy vs Integration

### ISSUE THREAD

**Issue by T-travis** [ActoKids/api#50]
Need to standardize the Errors from API GW for the UI to be able to display. 

**Description**
I created this bug for Jon's [PR](https://github.com/ActoKids/api/pull/45) for correct HTTP status responses, but the issue will also include the choice of Lambda Proxy vs Integration.  Here is an article that sums up the differences [link](https://medium.com/@lakshmanLD/lambda-proxy-vs-lambda-integration-in-aws-api-gateway-3a9397af0e6d) and we must now choose only one option now that the API team will be merging our Lambdas together (unless we don't merge them).

**Also...**
Investigate setting the CORS 'Access-Control-Allow-Origin' response header so as to restrict access to specified domain(s).   

-----------------------------------------------------------------------------------------------------------------

Regarding Lambda Proxy vs. Lambda Integration, the API team decided to use Lambda Integration for all methods.  This meant that API Gateway would have to be configured to return the proper HTTP status codes, since status codes were no longer being set in the Lambda functions.  

**WIKI PAGES**
[Configure API Gateway to return proper HTTP error codes](https://github.com/ActoKids/api/wiki/Configure-API-Gateway-to-return-proper-HTTP-error-codes) -- This describes the steps taken to update each method and associated Lambda to ensure that the API returned the proper HTTP status codes.  

[Setting the CORS response headers](https://github.com/ActoKids/api/wiki/Setting-CORS-response-headers) -- This describes steps required to set CORS configuration in API Gateway to restrict access control to a single origin.

**CORS demo**
There is a script in this page ( https://jradler.com/ ) that calls the /testing Resource of ak-jonathan-api-gateway.  If you open the console, you can see that the call was successful:  
![image](https://user-images.githubusercontent.com/27866709/54724983-98749e80-4b2a-11e9-8dbd-b454ba1c1655.png)

This page has the same script, but the call is not successful - it is blocked by CORS policy:
![image](https://user-images.githubusercontent.com/27866709/54725139-32d4e200-4b2b-11e9-9600-2830aa1ab71e.png)

A notable limitation of applying a mapping to the Access-Control-Allow-Origin header is that you cannot specify more than one domain, [nor can you use partial wildcards](https://www.w3.org/wiki/CORS_Enabled#How_can_I_participate.3F).  For example, the mapping cannot be '*.jradler.com'.  As a result, the script cannot run https://www.jradler.com
![image](https://user-images.githubusercontent.com/27866709/54725326-e76f0380-4b2b-11e9-8822-9d0779d9893f.png)

**ISSUES/BUGS CREATED IN DEVOPS REPO**
[Issue 59](https://github.com/ActoKids/devops/issues/59)

**TESTING/REVIEWS DONE**
[PR 69](https://github.com/ActoKids/api/pull/69#pullrequestreview-216935550)
[PR 68](https://github.com/ActoKids/api/pull/68#pullrequestreview-216907639)
[PR 79](https://github.com/ActoKids/api/pull/79#pullrequestreview-217043757)

**Time Spent**
Expected Time: 6 hours
Actual Time: 8 hours

**Comment by Enshaedn** [comment]
I have reviewed the wikis Jon created and they are well written and comprehensive. It is easy to follow them to implement both HTTP response codes and customize CORS.
