### ISSUE TITLE
Create PUT request for Events with logging

### ISSUE THREAD

**Issue by ZakBrinlee** [ActoKids/api#52]
Create a PUT request for editing ActoKids events with proper logging to CloudWatch. 
This is rolling over to Sprint 5 from the previous sprints -  relating to this Issue:
[Create PUT request for events](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/34)

**Please see related Issues for additional information/direction:**
[Logging for GET function](https://github.com/ActoKids/api/issues/15)
[Create GET request for Events](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/30)

**Logging standards to follow**
[Logging and Dashboard for API team ](https://github.com/ActoKids/api/issues/41)

Estimated time: 12 hours

**Comment by zach-daniels** [comment]
Estimated time: 12 hours

Actual time: 16 hours

Pull request tested by team members: https://github.com/ActoKids/api/pull/68

Wiki link: https://github.com/ActoKids/api/wiki/PUT-Request-for-Events
