### ISSUE TITLE
Configure Production environment

### ISSUE THREAD

**Issue by ZakBrinlee** [ActoKids/api#53]
Need to have the Production environment configured with the proper Lambdas. 
Production API Gateway needs to be configured and functional for UI team. 
CloudWatch needs a production environment dashboard.

Expected Time: 2 hours
Actual Time:

**Comment by Enshaedn** [comment]
Prod API Gateway is mostly set up now. POST, GET, and DELETE by event_id are currently functioning in the prod environment in every aspect (API Gateway, Lambda, Dynamo). Still need to finalize GET by event_id and PUT. Roughly 3 hours spent so far.

**Comment by Enshaedn** [comment]
## Accomplished:
Successfully configured the production environment API Gateway and CloudWatch dashboard.

## Sprint 5 Details:
- Pull Request (No code for this issue)
- Zach's CloudWatch [Wiki](https://github.com/ActoKids/api/wiki/Cloudwatch-Dashboard)
- Deployed Code (No code for this issue)

Estimated Time: 2 hours
Actual Time: 4 hours

## Testing:
Confirmed all endpoints created properly in API Gateway.
![image](https://user-images.githubusercontent.com/23545971/54499466-76331480-48cf-11e9-84f1-1b399b5a6f76.png)

POST test:
![image](https://user-images.githubusercontent.com/23545971/54499585-9a432580-48d0-11e9-8668-416fe53ff045.png)

GET test:
![image](https://user-images.githubusercontent.com/23545971/54499601-c8c10080-48d0-11e9-94d1-dd8d551a04cf.png)

GET by event_id test:
![image](https://user-images.githubusercontent.com/23545971/54499645-5a307280-48d1-11e9-9239-c65b2c945e82.png)

PUT by event_id test:
![image](https://user-images.githubusercontent.com/23545971/54499665-89df7a80-48d1-11e9-8887-5c7e59fd8c75.png)

DELETE by event_id test:
![image](https://user-images.githubusercontent.com/23545971/54499676-ab406680-48d1-11e9-95bb-11b2f2b1589b.png)

CloudWatch dashboard:
![image](https://user-images.githubusercontent.com/23545971/54499700-ef336b80-48d1-11e9-9ccd-c741d4a3b93d.png)
![image](https://user-images.githubusercontent.com/23545971/54499706-fd818780-48d1-11e9-9c37-6d9eb78c0434.png)
![image](https://user-images.githubusercontent.com/23545971/54499713-12f6b180-48d2-11e9-849d-1938155359ba.png)
![image](https://user-images.githubusercontent.com/23545971/54499720-1f7b0a00-48d2-11e9-80f3-5360e20d46ac.png)

### Tested: 
Please see my other [issue](https://github.com/ActoKids/api/issues/55) from this sprint.

### Bugs / Issues:
Please see my other [issue](https://github.com/ActoKids/api/issues/55) from this sprint.
